TellerEvent Class Reference
#include <TellerEvent.h>
Public Member Functions
 TellerEvent (float tellerServiceTime, float idleTime, TellerQueue * queue)
virtual ~TellerEvent ()
void action (float currentTime, TellerQueue **queues, int numTellers, EventQueue *simulationQueue)
 CustomerEvent * checkOtherQueues (TellerQueue **queues, int numTellers)
void editTime (float time)
float getTime ()
int getTotalServices ()
int getTotalIdles ()
float getIdleTime ()
float getServiceTime ()
Public Attributes
 TellerQueue * queue
Private Attributes
float tellerServiceTime
float idleTime
float totalServices
float totalIdles
float time
Constructor & Destructor Documentation
TellerEvent()
TellerEvent::TellerEvent (float tellerServiceTime, float idleTime, TellerQueue * queue)
Constructor
Parameters
tellerServiceTime time it takes for a teller to service a customer
idletTime time it takes for a teller to complete 1 idle
References idleTime, queue, tellerServiceTime, time, totalIdles, and totalServices.
~TellerEvent()
TellerEvent::~TellerEvent () [virtual]
Member Function Documentation
action()
void TellerEvent::action (float currentTime, TellerQueue ** queues, int numTellers, EventQueue * simulationQueue) [virtual]
Action event for tellerevent
Parameters
currentTime time of the simulation
queues Teller queues array
numTellers # of tellers Event queue
Reimplemented from Event .
References EventQueue::addEvent(), checkOtherQueues(), Customer::getCustomerEvent(), TellerQueue::getHead(), TellerQueue::getQueueSize(), getServiceTime(), idleTime, queue, TellerQueue::removeCustomer(), EventQueue::removeEvent(), CustomerEvent::setService(), CustomerEvent::setTime(), tellerServiceTime, time, totalIdles, and totalServices.
checkOtherQueues()
 CustomerEvent * TellerEvent::checkOtherQueues (TellerQueue ** queues, int numTellers)
Check other queues if the current queue is empty
Parameters
queues Teller queues to check
numTellers # of tellers
Returns
Pointer to customer event
References Customer::getCustomerEvent(), TellerQueue::getHead(), TellerQueue::getQueueSize(), queue, and TellerQueue::removeCustomer().
Referenced by action().
editTime()
void TellerEvent::editTime (float time)
getIdleTime()
float TellerEvent::getIdleTime ()
Retrieve idle time for the teller
Returns
idle time
References idleTime.
Referenced by runSim().
getServiceTime()
float TellerEvent::getServiceTime ()
Retrieve how long a teller services someone
Returns
time it takes to service
References tellerServiceTime.
Referenced by action(), and runSim().
getTime()
float TellerEvent::getTime () [virtual]
Retrieve event's time
Returns
event's time
Reimplemented from Event .
References time.
getTotalIdles()
int TellerEvent::getTotalIdles ()
Retrieve the total idles of the event
Returns
# of idle times
References totalIdles.
Referenced by runSim().
getTotalServices()
int TellerEvent::getTotalServices ()
Retrieve total services
Returns
# of services
References totalServices.
Referenced by runSim().
Member Data Documentation
idleTime
float TellerEvent::idleTime [private]
Referenced by action(), getIdleTime(), and TellerEvent().
queue
 TellerQueue* TellerEvent::queue
Referenced by action(), checkOtherQueues(), and TellerEvent().
tellerServiceTime
float TellerEvent::tellerServiceTime [private]
Referenced by action(), getServiceTime(), and TellerEvent().
time
float TellerEvent::time [private]
Referenced by action(), getTime(), and TellerEvent().
totalIdles
float TellerEvent::totalIdles [private]
Referenced by action(), getTotalIdles(), and TellerEvent().
totalServices
float TellerEvent::totalServices [private]
Referenced by action(), getTotalServices(), and TellerEvent().
The documentation for this class was generated from the following files:
 TellerEvent.h
 TellerEvent.cpp