Customer Class Reference
#include <Customer.h>
Public Member Functions
 Customer ()
virtual ~Customer ()
 Customer (CustomerEvent * event)
void setNextCustomer (Customer *cust)
 Customer * getNextCustomer ()
 CustomerEvent * getCustomerEvent ()
Public Attributes
 Customer * nextCustomer
 CustomerEvent * event
Constructor & Destructor Documentation
Customer() [1/2]
Customer::Customer ()
~Customer()
Customer::~Customer () [virtual]
Customer() [2/2]
Customer::Customer (CustomerEvent * event)
References event, and nextCustomer.
Member Function Documentation
getCustomerEvent()
 CustomerEvent * Customer::getCustomerEvent ()
Retrieves the customer's event
Returns
Pointer to event
References event.
Referenced by TellerEvent::action(), and TellerEvent::checkOtherQueues().
getNextCustomer()
 Customer * Customer::getNextCustomer ()
Retrieve the nextCustomer
Returns
Pointer to the next customer
References nextCustomer.
Referenced by TellerQueue::removeCustomer().
setNextCustomer()
void Customer::setNextCustomer (Customer * cust)
Set nextCustomer to cust
Parameters
cust Pointer to new customer
References nextCustomer.
Referenced by TellerQueue::addCustomer().
Member Data Documentation
event
 CustomerEvent* Customer::event
Referenced by Customer(), and getCustomerEvent().
nextCustomer
 Customer* Customer::nextCustomer
Referenced by TellerQueue::addCustomer(), Customer(), getNextCustomer(), and setNextCustomer().
The documentation for this class was generated from the following files:
 Customer.h
 Customer.cpp