CustomerEvent Class Reference
#include <CustomerEvent.h>
Public Member Functions
 CustomerEvent (float startTime)
virtual ~CustomerEvent ()
void action (float currentTime, TellerQueue **queues, int numTellers, EventQueue *simulationQueue)
float getTime ()
void setService ()
void setTime (float t)
bool getServicing ()
int getEndTime ()
int getStartTime ()
 TellerQueue * findShortestLine (TellerQueue **q, int numTellers)
Private Attributes
float startTime
float time
float endTime
bool receivingService
Constructor & Destructor Documentation
CustomerEvent()
CustomerEvent::CustomerEvent (float beginningTime)
Constructor
Parameters
beginningTime Start time for the event
References endTime, receivingService, startTime, and time.
~CustomerEvent()
CustomerEvent::~CustomerEvent () [virtual]
Member Function Documentation
action()
void CustomerEvent::action (float currentTime, TellerQueue ** queues, int numTellers, EventQueue * simulationQueue) [virtual]
The action to be called on by the Event Queue
Parameters
currentTime time to update endTime
queues Teller queues to check/use
numTellers # of teller queues
simulationQueue Event Queue to update for action
Reimplemented from Event .
References TellerQueue::addCustomer(), endTime, findShortestLine(), receivingService, and EventQueue::removeEvent().
findShortestLine()
 TellerQueue * CustomerEvent::findShortestLine (TellerQueue ** lines, int numLines)
Retrieve the shortest line amongt a 2d array of tellerqueues
Parameters
lines Pointer to teller queues
numLines # of teller queues
Returns
The shortest line
References TellerQueue::getQueueSize().
Referenced by action().
getEndTime()
int CustomerEvent::getEndTime ()
Retrieve end time
Returns
end time for the event
References endTime.
Referenced by runSim().
getServicing()
bool CustomerEvent::getServicing ()
Retrieve service status
Returns
True if processed, false if unprocessed
References receivingService.
getStartTime()
int CustomerEvent::getStartTime ()
Retrieve start Time
Returns
start time for event
References startTime.
Referenced by runSim().
getTime()
float CustomerEvent::getTime () [virtual]
Retreieve event time
Returns
event time
Reimplemented from Event .
References time.
setService()
void CustomerEvent::setService ()
Set whether this event has been processed by a teller
References receivingService.
Referenced by TellerEvent::action().
setTime()
void CustomerEvent::setTime (float currentTime)
Update the events current time
Parameters
currentTime Time to update to
References time.
Referenced by TellerEvent::action().
Member Data Documentation
endTime
float CustomerEvent::endTime [private]
Referenced by action(), CustomerEvent(), and getEndTime().
receivingService
bool CustomerEvent::receivingService [private]
Referenced by action(), CustomerEvent(), getServicing(), and setService().
startTime
float CustomerEvent::startTime [private]
Referenced by CustomerEvent(), and getStartTime().
time
float CustomerEvent::time [private]
Referenced by CustomerEvent(), getTime(), and setTime().
The documentation for this class was generated from the following files:
 CustomerEvent.h
 CustomerEvent.cpp