EventQueue Class Reference
#include <EventQueue.h>
Public Member Functions
 EventQueue ()
virtual ~EventQueue ()
 Event * getHead ()
void removeEvent ()
void addEvent (Event *event)
int getQueueSize ()
 Event * getEventAt (int index)
Private Attributes
 Event * head
int size
Constructor & Destructor Documentation
EventQueue()
EventQueue::EventQueue ()
Constructor, set head to nullptr and size to 0
References head, and size.
~EventQueue()
EventQueue::~EventQueue () [virtual]
Member Function Documentation
addEvent()
void EventQueue::addEvent (Event * event)
Add event to the queue
Parameters
event Pointer to event to add
References getEventAt(), Event::getNextEvent(), Event::getTime(), head, Event::setNext(), and size.
Referenced by TellerEvent::action(), and main().
getEventAt()
 Event * EventQueue::getEventAt (int index)
Retrieve even in the queue at a certain index
Parameters
index Event to retrieve
References Event::getNextEvent(), head, and size.
Referenced by addEvent().
getHead()
 Event * EventQueue::getHead ()
Retrieve the head of the event queue
Returns
head/1st of event queue
References head.
Referenced by runSim().
getQueueSize()
int EventQueue::getQueueSize ()
Retrieve queue size
Returns
size of event queue
References size.
Referenced by runSim().
removeEvent()
void EventQueue::removeEvent ()
Remove event from the event queue
References Event::getNextEvent(), head, and size.
Referenced by CustomerEvent::action(), and TellerEvent::action().
Member Data Documentation
head
 Event* EventQueue::head [private]
Referenced by addEvent(), EventQueue(), getEventAt(), getHead(), and removeEvent().
size
int EventQueue::size [private]
Referenced by addEvent(), EventQueue(), getEventAt(), getQueueSize(), and removeEvent().
The documentation for this class was generated from the following files:
 EventQueue.h
 EventQueue.cpp