mystruct.c File Reference
#include <string.h>
#include <stdlib.h>
#include `mystruct.h`
#include <stdio.h>
#include <time.h>
Functions
struct Employee * makeEmployee (int birth, int start, const char *name)
struct Employee ** makeArrayEmployees (size_t n)
struct Employee * makeRandomEmployee ()
void changeBirthYear (struct Employee *e)
struct Employee ** duplicateEmployees (struct Employee **e, size_t n)
struct Employee ** deepCopyEmployees (struct Employee **e, size_t n)
void freeEmployees (struct Employee **e, size_t n)
char * getRandomName ()
void printEmployees (struct Employee **e, size_t n)
void printEmployee (struct Employee *e)
char getRandomLowerLetter ()
char getRandomUpperLetter ()
int getRandomInt ()
int getRandomNameLength ()
void seedRand ()
Function Documentation
changeBirthYear()
void changeBirthYear (struct Employee * e)
Changes the birth year of an employee
Parameters
e Pointer to an employee
References Employee::birth_year.
Referenced by main().
deepCopyEmployees()
struct Employee** deepCopyEmployees (struct Employee ** e, size_t n)
Deep Copy of employees
Parameters
e Pointer to array of employees
n # of employees to copy
Returns
Pointer to newly deep copied array
References Employee::birth_year, Employee::name, and Employee::start_year.
Referenced by main().
duplicateEmployees()
struct Employee** duplicateEmployees (struct Employee ** e, size_t n)
Shallow copy of new array of employees
Parameters
e Pointer to array of employees
n size of employees to duplicate
Returns
Pointer to array of new employees
Referenced by main().
freeEmployees()
void freeEmployees (struct Employee ** e, size_t n)
Frees memory from each employee and then the array holding the employees
Parameters
e Pointer pointing to an array holding pointers of employees
n # of employees to free
Referenced by main().
getRandomInt()
int getRandomInt ()
Generate a random year from 1-9999
Returns
a year from 1 - 9999
Referenced by makeRandomEmployee().
getRandomLowerLetter()
char getRandomLowerLetter ()
Generate random lower case letter
Returns
A lower case letter
Referenced by getRandomName().
getRandomName()
char* getRandomName ()
Generate a random name
Returns
Return a random name
References getRandomLowerLetter(), getRandomNameLength(), getRandomUpperLetter(), and Employee::name.
Referenced by makeRandomEmployee().
getRandomNameLength()
int getRandomNameLength ()
Generate a random name length
Returns
random name length 1-11
Referenced by getRandomName().
getRandomUpperLetter()
char getRandomUpperLetter ()
Generate an upper case letter
Returns
An upper case letter
Referenced by getRandomName().
makeArrayEmployees()
struct Employee** makeArrayEmployees (size_t n)
Creates array of employees
Parameters
n Size to make
Returns
Pointer to new struct
References makeRandomEmployee().
Referenced by main().
makeEmployee()
struct Employee* makeEmployee (int birth, int start, const char * name)
mystruct.c
Author
Mike Ciaraldi Allocates an Employee struct and fills in its fields
Parameters
birth Year the emploee was born.
start Year the employee started with the company.
name String containing employee's name
Returns
Pointer to Employee struct, newly allocated from the heap.
References Employee::birth_year, Employee::name, and Employee::start_year.
Referenced by main().
makeRandomEmployee()
struct Employee* makeRandomEmployee ()
Create a random employ with random info
Returns
Pointer to struct
References Employee::birth_year, getRandomInt(), getRandomName(), Employee::name, and Employee::start_year.
Referenced by main(), and makeArrayEmployees().
printEmployee()
void printEmployee (struct Employee * e)
Print single employee
Parameters
e Pointer to employee
References Employee::birth_year, Employee::name, and Employee::start_year.
Referenced by main().
printEmployees()
void printEmployees (struct Employee ** e, size_t n)
Print employees
Parameters
e Pointer to array of employees
n Number of employees to print
References Employee::birth_year, Employee::name, and Employee::start_year.
Referenced by main().
seedRand()
void seedRand ()
Seeds the random function
Referenced by main().