TellerQueue Class Reference
#include <TellerQueue.h>
Public Member Functions
 TellerQueue ()
virtual ~TellerQueue ()
void addCustomer (Customer *customer)
 Customer * getHead ()
int getQueueSize ()
void removeCustomer ()
Private Attributes
 Customer * head
int size
Constructor & Destructor Documentation
TellerQueue()
TellerQueue::TellerQueue ()
References head, and size.
~TellerQueue()
TellerQueue::~TellerQueue () [virtual]
Member Function Documentation
addCustomer()
void TellerQueue::addCustomer (Customer * customer)
Add customer to queue
Parameters
*customer Pointer to customer
Returns
True if added, false if not
References head, Customer::nextCustomer, Customer::setNextCustomer(), and size.
Referenced by CustomerEvent::action().
getHead()
 Customer * TellerQueue::getHead ()
Returns customer at the beginning of the line
Returns
Pointer to 1st in line customer
References head.
Referenced by TellerEvent::action(), TellerEvent::checkOtherQueues(), and Teller::updateBreakStatus().
getQueueSize()
int TellerQueue::getQueueSize ()
Returns the last customer in the queue
Returns
Pointer to last customer Returns size of teller queue
Size of queue
References size.
Referenced by TellerEvent::action(), TellerEvent::checkOtherQueues(), and CustomerEvent::findShortestLine().
removeCustomer()
void TellerQueue::removeCustomer ()
Remove and return the next customer
Returns
Pointer to next customer
References Customer::getNextCustomer(), head, and size.
Referenced by TellerEvent::action(), and TellerEvent::checkOtherQueues().
Member Data Documentation
head
 Customer* TellerQueue::head [private]
Referenced by addCustomer(), getHead(), removeCustomer(), and TellerQueue().
size
int TellerQueue::size [private]
Referenced by addCustomer(), getQueueSize(), removeCustomer(), and TellerQueue().
The documentation for this class was generated from the following files:
 TellerQueue.h
 TellerQueue.cpp