Teller Class Reference
#include <Teller.h>
Public Member Functions
 Teller (int num)
virtual ~Teller ()
void updateBreakStatus (TellerQueue *line)
int getIdleTime ()
Public Attributes
bool onBreak
bool processing
int tellerNum
Private Member Functions
void setIdleTime ()
Private Attributes
const int idleTimeConst = 600
int idleTime
Constructor & Destructor Documentation
Teller()
Teller::Teller (int num)
References onBreak, processing, setIdleTime(), and tellerNum.
~Teller()
Teller::~Teller () [virtual]
Member Function Documentation
getIdleTime()
int Teller::getIdleTime ()
Returns idle time of teller
Returns
Time to idlek
References idleTime.
setIdleTime()
void Teller::setIdleTime () [private]
Sets idle time of teller
References idleTime.
Referenced by Teller().
updateBreakStatus()
void Teller::updateBreakStatus (TellerQueue * line)
Check if the teller has any customers in some queue before changing idle status
Parameters
*line Pointer to tellerqueue
References TellerQueue::getHead(), and onBreak.
Member Data Documentation
idleTime
int Teller::idleTime [private]
Referenced by getIdleTime(), and setIdleTime().
idleTimeConst
const int Teller::idleTimeConst = 600 [private]
onBreak
bool Teller::onBreak
Referenced by Teller(), and updateBreakStatus().
processing
bool Teller::processing
Referenced by Teller().
tellerNum
int Teller::tellerNum
Referenced by Teller().
The documentation for this class was generated from the following files:
 Teller.h
 Teller.cpp