mystring.c File Reference
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include `mystring.h`
Functions
char * mystrdup1 (const char *src)
char * mystrcpy1 (char *dest, const char *src)
char * mystrncpy1 (char *dest, const char *src, size_t n)
char * mystrcat1 (char *dest, const char *src)
char * mystrncat1 (char *dest, const char *src, size_t n)
char * mystrdup2 (const char *src)
char * mystrndup1 (const char *src, size_t n)
size_t mystrlen1 (const char *s)
size_t mystrlen2 (const char *s)
Function Documentation
mystrcat1()
char* mystrcat1 (char * dest, const char * src)
Concatenates two strings together
Parameters
dest Pointer to destination string
src Pointer to src string
Returns
Pointer to destination string after src is concatenated into dest
References mystrlen2().
Referenced by main().
mystrcpy1()
char* mystrcpy1 (char * dest, const char * src)
Copy src string into target string and return a pointer to target
Parameters
target Pointer to target string to copy to
src Pointer to src string to copy from
Returns
Pointer to newly copied-to target
Referenced by main().
mystrdup1()
char* mystrdup1 (const char * src)
mystring.c
Author
Mike Ciaraldi My own versions of some of the C-style string functions Duplicates a C-style string.
Parameters
src Pointer to string to be copied
Returns
Pointer to freshly-allocated string containing a duplicate of src or null if no memory is available
References mystrlen1().
Referenced by main().
mystrdup2()
char* mystrdup2 (const char * src)
Copies input string and returns the copied version
Parameters
src Pointer to input string
Returns
Pointer to new string containing char elements of the src string as a copy, or null if not enough memory
References mystrlen2().
Referenced by main().
mystrlen1()
size_t mystrlen1 (const char * s)
Calculates the length of a string, not including null character '\0' This version iterates through the char array via array subscripting
Parameters
s Pointer to string to calculate length of
Returns
size_t Size of the string
Referenced by main(), mystrdup1(), and mystrndup1().
mystrlen2()
size_t mystrlen2 (const char * s)
Calculates the length of a string, not including null character '\0' via poiner arithmatic
Parameters
s Pointer to string to calculate length of
Returns
size_t Size of the string
Referenced by mystrcat1(), mystrdup2(), and mystrncat1().
mystrncat1()
char* mystrncat1 (char * dest, const char * src, size_t n)
Concatenates n bytes of src string to dest string, adding null terminator at the end
Parameters
dest Destination string to concatenate to from src
src Source to concatenate from
Returns
pointer to destination after concatenation
References mystrlen2().
Referenced by main().
mystrncpy1()
char* mystrncpy1 (char * dest, const char * src, size_t n)
Copies n # of bytes from src to dest, adding null terminators if mystrlen2(src) < n
Parameters
dest Destination of string to copy to from src
src Source to copy from
n # of bytes to copy
Returns
Pointer to destination after copy
Referenced by main(), and mystrndup1().
mystrndup1()
char* mystrndup1 (const char * src, size_t n)
Duplicate n bytes of from src into a new string holding the right amount of memory
Parameters
src Pointer to source string to duplicate from
n Number of bytes to duplicate
Returns
Pointer to new string containing duplicated string and n number of bytes
References mystrlen1(), and mystrncpy1().
Referenced by main().