structest.c File Reference
#include <stdio.h>
#include `mystruct.h`
Functions
int main (int atgc, char *argv[])
Function Documentation
main()
int main (int atgc, char * argv[])
References duplicateEmployees(), makeArrayEmployees(), makeEmployee(), makeRandomEmployee(), printEmployee(), and printEmployees().